### PR TITLE
Moving Caching logic to central file

### PR DESCRIPTION
**Pull request by bartelink**
Prep/cleanup in advance of #196 potentially introducing a third clone of the caching logic into the codebase

### CODE REVIEW

**Comment by bartelink** [comment]
@DSilence Any idea whether there's a running system out there that still relies on it? I'm thinking of removing it (i.e. this PR) 4.x unless this actually got used

**Comment by bartelink** [comment]
Caching.fs will move into EventstoreDb and be linked into EventStore and SqlStreamStore rather than living in Equinox.Core (see #196)

**Comment by DSilence** [comment]
Not sure there is anything in prod currently relying on async implementation. Could be useful for file-based cache though (or anything network related)

**Comment by bartelink** [comment]
@DSilence hard to argue against that reasoning (even if speculative!); thanks for the nudge; reverted in [6be1b5a](https://github.com/jet/equinox/pull/318/commits/6be1b5a5528fa71c8a68af1bbde6406d7475c79c)
I guess it also makes for there to be asynchrony here if #61 ever happens, given that's definitely Async in nature

**Pull request merged**
